name: Deploy dev

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEPLOY_URL: 'https://dev.danceweekend.art'
          envkey_NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.TEST_NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
          envkey_PAYPAL_SECRET: ${{ secrets.TEST_PAYPAL_SECRET }}
          envkey_PAYPAL_API_URL: ${{ secrets.TEST_PAYPAL_API_URL }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}
          envkey_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          envkey_NOTION_DATABASE_LIVE: ${{ secrets.NOTION_DATABASE_LIVE_TEST }}
          envkey_NOTION_DATABASE_ONLINE: ${{ secrets.NOTION_DATABASE_ONLINE_TEST }}
          envkey_FTP_HOST: ${{ secrets.FTP_HOST_TEST }}
          envkey_FTP_USER: ${{ secrets.FTP_USER_TEST }}
          envkey_FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_TEST }}
          envkey_FTP_DIR: ${{ secrets.FTP_DIR_TEST }}
          envkey_FTP_PHOTO_DIR: ${{ secrets.FTP_PHOTO_DIR_TEST }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/vkluchenkov/danceweekend:latest-dev .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/vkluchenkov/danceweekend:latest-dev

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/vkluchenkov/danceweekend:latest-dev
            docker stop Danceweekend-dev
            docker rm Danceweekend-dev
            docker run -d -p 49162:3000 --name=Danceweekend-dev --restart=always --pull=always ghcr.io/vkluchenkov/danceweekend:latest-dev
            docker system prune -f
