name: Deploy main

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEPLOY_URL: 'https://danceweekend.art'
          envkey_NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
          envkey_PAYPAL_SECRET: ${{ secrets.PAYPAL_SECRET }}
          envkey_PAYPAL_API_URL: ${{ secrets.PAYPAL_API_URL }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}
          envkey_NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          envkey_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          envkey_NOTION_DATABASE_LIVE: ${{ secrets.NOTION_DATABASE_LIVE }}
          envkey_NOTION_DATABASE_ONLINE: ${{ secrets.NOTION_DATABASE_ONLINE }}
          envkey_FTP_HOST: ${{ secrets.FTP_HOST_LIVE }}
          envkey_FTP_USER: ${{ secrets.FTP_USER_LIVE }}
          envkey_FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_LIVE }}
          envkey_FTP_DIR: ${{ secrets.FTP_DIR_LIVE }}
          envkey_FTP_PHOTO_DIR: ${{ secrets.FTP_PHOTO_DIR }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/vkluchenkov/danceweekend:latest-main .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/vkluchenkov/danceweekend:latest-main

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/vkluchenkov/danceweekend:latest-main
            docker stop Danceweekend-main
            docker rm Danceweekend-main
            docker run -d -p 49161:3000 --name=Danceweekend-main --restart=always --pull=always ghcr.io/vkluchenkov/danceweekend:latest-main
            docker system prune -f
