name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
      SERVER: production
      NEXT_PUBLIC_PROMO_PERIOD: ${{ vars.NEXT_PUBLIC_PROMO_PERIOD }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t cloud.canister.io:5000/vkluchenkov/danceweekend:latest-main .
      
    - name: Login to Canister
      run: docker login --username=${{ secrets.CANISTERLOGIN }} --password=${{ secrets.CANISTERPASS }} cloud.canister.io:5000
      
    - name: Push the Docker image
      run: docker push cloud.canister.io:5000/vkluchenkov/danceweekend:latest-main
    
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.MASTERWEBHOOK }}
        method: 'POST'
